### ISSUE TITLE
Responsive del header

### ISSUE THREAD

**Issue by jforni** [YohaBelmonte/ecommerce-front#55]
En un tamaño de pantalla relativamente amplio todavía (1350x780), se me desacomodan los íconos del carrito de compra, favoritos, usuario y el input de Buscar, lo que visualmente no queda muy bien. 

![image](https://user-images.githubusercontent.com/6042663/233386163-7791c3cc-227b-4a8f-b7ad-4f3674bb76dc.png)

**Comment by YohaBelmonte** [comment]
Posicionamiento de los iconos corregido!
Con respecto a la posicion del input del buscador era parte del diseño que quede abajo
