### ISSUE TITLE
Tarjetas de productos en vista móbil

### ISSUE THREAD

**Issue by jforni** [YohaBelmonte/ecommerce-front#56]
Recomiendo el tamaño de las tarjetas un poco más grandes y centradas.

![image](https://user-images.githubusercontent.com/6042663/234701920-45205232-d07a-4d4a-a957-8c4729c086e3.png)

**Comment by YohaBelmonte** [comment]
Vista en mobile y tablet corregidas

![image](https://user-images.githubusercontent.com/111397151/235691513-245b50bf-afb6-42bf-9a85-a093de4d184d.png)
![image](https://user-images.githubusercontent.com/111397151/235691605-eb6d64c7-9479-411a-8127-f3159ba09015.png)
