### ISSUE TITLE
Tarjetas en vista navegador web de computadora

### ISSUE THREAD

**Issue by jforni** [YohaBelmonte/ecommerce-front#57]
Noto que el bloque de tarjetas no está centrado. 
![image](https://user-images.githubusercontent.com/6042663/234702806-f7637bd5-7156-48f6-a159-44133f943be7.png)

**Comment by YohaBelmonte** [comment]
Buen dia! ya se pudo corregir el error! se supone que deberia aparecer la publicidad a la derecha 
![image](https://user-images.githubusercontent.com/111397151/235691256-787099b7-c63c-4f15-83a6-7a6011b02070.png)
